### ISSUE TITLE
VSHiveStub.exe failed: PkgdefManagement failed to create application: "0x80070057"

### ISSUE THREAD

**Issue by apobekiaris** [microsoft/vsixbootstrapper#14]
bootstrapper fails with the next log while the plugin is installed and can be uninstalled manually

>5/31/2019 7:48:11 AM - Microsoft VSIX Installer
5/31/2019 7:48:11 AM - -------------------------------------------
5/31/2019 7:48:11 AM - vsixinstaller.exe version:
5/31/2019 7:48:11 AM - 16.2.24
5/31/2019 7:48:11 AM - -------------------------------------------
5/31/2019 7:48:11 AM - Command line parameters:
5/31/2019 7:48:11 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,/u:Xpand.VSIX.eXpandFramework.4ab62fb3-4108-4b4d-9f45-8a265487d3dc
5/31/2019 7:48:11 AM - -------------------------------------------
5/31/2019 7:48:11 AM - Microsoft VSIX Installer
5/31/2019 7:48:11 AM - -------------------------------------------
5/31/2019 7:48:12 AM - BEGIN: Processing extension pack
5/31/2019 7:48:13 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
5/31/2019 7:48:13 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\Desktop SDK\extension.vsixmanifest'
5/31/2019 7:48:13 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\SDK ARM Additions\extension.vsixmanifest'
5/31/2019 7:48:13 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\Windows Store SDK\extension.vsixmanifest'
5/31/2019 7:48:13 AM - Skipping 'C:\Users\Tolis\AppData\Local\Microsoft SDKs' as it doesn't exist
5/31/2019 7:48:14 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
5/31/2019 7:48:14 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\DataDesign\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\DesignTools\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Diff\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Editor\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ErrorList\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ProductUpdate\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ReferenceManager\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\TemplateProviders\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\XamlLanguageService\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Platform\Debugger\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Platform\NavigateTo\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Platform\ParallelDebugger\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Platform\Shell\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Platform\TreeNavigation\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Architecture Tools\GraphProviderPackage\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Language\CallHierarchy\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Language\GenerateType\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Roslyn\Expression Evaluators\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Roslyn\Language Services\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Roslyn\Telemetry\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Roslyn\VisualStudio Interactive Components\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Web\ASPX\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Web\Exports\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Platform\NavigateTo\FileProvider\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Platform\TreeNavigation\GraphProvider\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Platform\Visual Studio MPF\14.0\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ExceptionAssistant\SmartTags\10.0\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SQL SERVER\140\TOOLS\BINN\MANAGEMENTSTUDIO\EXTENSIONS\APPLICATION\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SQL SERVER\140\TOOLS\BINN\MANAGEMENTSTUDIO\EXTENSIONS\Application\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SQL SERVER\140\TOOLS\BINN\MANAGEMENTSTUDIO\Extensions\Application\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\Desktop SDK\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\SDK ARM Additions\extension.vsixmanifest'
5/31/2019 7:48:14 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\Windows Store SDK\extension.vsixmanifest'
5/31/2019 7:48:15 AM - Skipping 'C:\Users\Tolis\AppData\Local\Microsoft SDKs' as it doesn't exist
5/31/2019 7:48:15 AM - END: Processing extension pack
5/31/2019 7:48:16 AM - System.InvalidOperationException: VSHiveStub.exe failed: PkgdefManagement failed to create application: "0x80070057".
   at VSIXInstaller.LocationBasedSKU.get_RegRootHiveOverride()
   at VSIXInstaller.SupportedVSSKU.InitializeSettingsManager()
   at VSIXInstaller.SupportedVSSKU.get_Host()
   at VSIXInstaller.SupportedVSSKU.CreateExtensionEngine()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToUnInstall(IStateData stateData, List`1 supportedSKUs, String uninstallableVsixId, String extensionPackParentName, List`1 uninstallVsixIds)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToUnInstall(IStateData stateData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by heaths** [comment]
Will need additional information. Please file feedback from with Visual Studio which will collect all the necessary data and file to the appropriate team. This tool is just a pass-through.

**Comment by lnicolae** [comment]
Same error with lates version 2019.3.22.0

6/27/2019 12:31:33 AM - Microsoft VSIX Installer
6/27/2019 12:31:33 AM - -------------------------------------------
6/27/2019 12:31:33 AM - vsixinstaller.exe version:
6/27/2019 12:31:33 AM - 16.2.2061
6/27/2019 12:31:33 AM - -------------------------------------------
6/27/2019 12:31:33 AM - Command line parameters:
6/27/2019 12:31:33 AM - C:\program files (x86)\microsoft visual studio\installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,/u:c997d569-ee8e-4947-a46f-9a0717ce39a0
6/27/2019 12:31:33 AM - -------------------------------------------
6/27/2019 12:31:33 AM - Microsoft VSIX Installer
6/27/2019 12:31:33 AM - -------------------------------------------
6/27/2019 12:31:38 AM - BEGIN: Processing extension pack
6/27/2019 12:31:38 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
6/27/2019 12:31:38 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\Desktop SDK\extension.vsixmanifest'
6/27/2019 12:31:39 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\SDK ARM Additions\extension.vsixmanifest'
6/27/2019 12:31:39 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\Windows Store SDK\extension.vsixmanifest'
6/27/2019 12:31:39 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\8.0\Metro SDK\extension.vsixmanifest'
6/27/2019 12:31:39 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\8.1\Desktop SDK\extension.vsixmanifest'
6/27/2019 12:31:39 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\8.1\Windows Store SDK\extension.vsixmanifest'
6/27/2019 12:31:39 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SDKS\UAP\v0.8.0.0\ExtensionSDKs\SQLite.UAP.2015\3.8.11.1\extension.vsixmanifest'
6/27/2019 12:31:39 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SDKS\WINDOWS\v8.1\ExtensionSDKs\Microsoft.WinJS.Shared\VSIX\extension.vsixmanifest'
6/27/2019 12:31:40 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SDKS\WINDOWSPHONEAPP\v8.1\ExtensionSDKs\Microsoft.Advertising.Mobile.Display\8.1\extension.vsixmanifest'
6/27/2019 12:31:40 AM - Skipping 'C:\Users\Lautas\AppData\Local\Microsoft SDKs' as it doesn't exist
6/27/2019 12:31:42 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ClientDiagnostics\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\DesignTools\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\TypeScript\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\VSI\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\XamlLanguageService\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ClientDiagnostics\AppResponsiveness\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ClientDiagnostics\XamlDiagnostics\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\TeamFoundation\Team Explorer\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\VC\Editor\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\VC\NavigateTo\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\VC\Project\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Architecture Tools\Providers\NativeCode\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ProductUpdate\WPEmulator\8.1\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Web\Razor\v2.0\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Web\Razor\v3.0\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Web\Razor\v4.0\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Web\Razor\v4.0_RC1\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\WebClient\Diagnostics\DebugIEOnPhone\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SQL SERVER\130\TOOLS\BINN\MANAGEMENTSTUDIO\EXTENSIONS\APPLICATION\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SQL SERVER\130\TOOLS\BINN\MANAGEMENTSTUDIO\EXTENSIONS\Application\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SQL SERVER\130\TOOLS\BINN\MANAGEMENTSTUDIO\Extensions\Application\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\Desktop SDK\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\SDK ARM Additions\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\Windows Store SDK\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\8.0\Metro SDK\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\8.1\Desktop SDK\extension.vsixmanifest'
6/27/2019 12:31:42 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\8.1\Windows Store SDK\extension.vsixmanifest'
6/27/2019 12:31:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SDKS\UAP\v0.8.0.0\ExtensionSDKs\SQLite.UAP.2015\3.8.11.1\extension.vsixmanifest'
6/27/2019 12:31:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SDKS\WINDOWS\v8.1\ExtensionSDKs\Microsoft.WinJS.Shared\VSIX\extension.vsixmanifest'
6/27/2019 12:31:43 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SDKS\WINDOWSPHONEAPP\v8.1\ExtensionSDKs\Microsoft.Advertising.Mobile.Display\8.1\extension.vsixmanifest'
6/27/2019 12:31:43 AM - Skipping 'C:\Users\Lautas\AppData\Local\Microsoft SDKs' as it doesn't exist
6/27/2019 12:31:45 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ClientDiagnostics\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\DesignTools\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\TypeScript\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\VSI\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\XamlLanguageService\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ClientDiagnostics\AppResponsiveness\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ClientDiagnostics\XamlDiagnostics\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\TeamFoundation\Team Explorer\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\VC\Editor\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\VC\NavigateTo\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\VC\Project\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Architecture Tools\Providers\NativeCode\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\ProductUpdate\WPEmulator\8.1\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Web\Razor\v2.0\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Web\Razor\v3.0\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Web\Razor\v4.0\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\Web\Razor\v4.0_RC1\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\WebClient\Diagnostics\DebugIEOnPhone\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SQL SERVER\140\TOOLS\BINN\MANAGEMENTSTUDIO\EXTENSIONS\APPLICATION\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SQL SERVER\140\TOOLS\BINN\MANAGEMENTSTUDIO\EXTENSIONS\Application\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SQL SERVER\140\TOOLS\BINN\MANAGEMENTSTUDIO\Extensions\Application\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Capping recursion at 5 directories in each extension root due to 'default limit'.
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\Desktop SDK\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\SDK ARM Additions\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\Windows Store SDK\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\8.0\Metro SDK\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\8.1\Desktop SDK\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\8.1\Windows Store SDK\extension.vsixmanifest'
6/27/2019 12:31:45 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SDKS\UAP\v0.8.0.0\ExtensionSDKs\SQLite.UAP.2015\3.8.11.1\extension.vsixmanifest'
6/27/2019 12:31:46 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SDKS\WINDOWS\v8.1\ExtensionSDKs\Microsoft.WinJS.Shared\VSIX\extension.vsixmanifest'
6/27/2019 12:31:46 AM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SDKS\WINDOWSPHONEAPP\v8.1\ExtensionSDKs\Microsoft.Advertising.Mobile.Display\8.1\extension.vsixmanifest'
6/27/2019 12:31:46 AM - Skipping 'C:\Users\Lautas\AppData\Local\Microsoft SDKs' as it doesn't exist
6/27/2019 12:31:46 AM - END: Processing extension pack
6/27/2019 12:31:46 AM - System.InvalidOperationException: VSHiveStub.exe failed: PkgdefManagement failed to create application: "0x80070057".
   at VSIXInstaller.LocationBasedSKU.get_RegRootHiveOverride()
   at VSIXInstaller.SupportedVSSKU.InitializeSettingsManager()
   at VSIXInstaller.SupportedVSSKU.get_Host()
   at VSIXInstaller.SupportedVSSKU.CreateExtensionEngine()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToUnInstall(IStateData stateData, List`1 supportedSKUs, String uninstallableVsixId, String extensionPackParentName, List`1 uninstallVsixIds)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToUnInstall(IStateData stateData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
