### ISSUE TITLE
Memory Leaks in CommandLine class

### ISSUE THREAD

**Issue by dmitry-lipetsk** [microsoft/vsixbootstrapper#16]
Hello,

https://github.com/microsoft/vsixbootstrapper/blob/46c15f89d3f4d095b469727b61f756fe5ce0779d/src/VSIXBootstrapper.Shared/CommandLine.h#L25-L43

If the code in line 42 will throw, destructor (~CommandLine) not will called

https://github.com/microsoft/vsixbootstrapper/blob/46c15f89d3f4d095b469727b61f756fe5ce0779d/src/VSIXBootstrapper.Shared/CommandLine.h#L64-L70

As result, m_rgwszArgs will not released.

I'm right?

It is not critical problem, but (I think) such problems should not be in MS code :)

**Comment by heaths** [comment]
Thanks for pointing this out. Bugs can happen in any code. The likelihood of the vector range constructor throwing are very low since the arguments were already validated. Out of memory is most likely (to allocate the vector itself) but is always fatal. Even still, this is a short-lived process that could only terminate with an error (crash or gracefully).
